version: "3.7"

services:
  pmss:
    build: .
    command: pmss
  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pmss
      MARIADB_USER: pmss
      MARIADB_PASSWORD: pmss
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}