// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/google/uuid"
	"github.com/overlordtm/pmss/pkg/datastore"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// File defines model for File.
type File struct {
	Ctime    *int64  `json:"ctime,omitempty"`
	FileMode uint32  `json:"fileMode"`
	Md5      *string `json:"md5,omitempty"`
	Mtime    int64   `json:"mtime"`
	Path     string  `json:"path"`
	Sha1     *string `json:"sha1,omitempty"`
	Sha256   *string `json:"sha256,omitempty"`
	Size     int64   `json:"size"`
}

// HashQueryResponse defines model for HashQueryResponse.
type HashQueryResponse struct {
	File   *KnownFile           `json:"file,omitempty"`
	Status datastore.FileStatus `json:"status"`
}

// KnownFile defines model for KnownFile.
type KnownFile struct {
	Md5    *string `json:"md5,omitempty"`
	Sha1   *string `json:"sha1,omitempty"`
	Sha256 *string `json:"sha256,omitempty"`
	Size   *int64  `json:"size,omitempty"`
}

// NewReportRequest defines model for NewReportRequest.
type NewReportRequest struct {
	Files       []File     `json:"files"`
	Hostname    string     `json:"hostname"`
	MachineId   string     `json:"machineId"`
	ReportRunId *uuid.UUID `json:"reportRunId,omitempty"`
}

// NewReportResponse defines model for NewReportResponse.
type NewReportResponse struct {
	Files []ReportFile `json:"files"`
	Id    uuid.UUID    `json:"id"`
}

// ReportFile defines model for ReportFile.
type ReportFile struct {
	Path   string               `json:"path"`
	Status datastore.FileStatus `json:"status"`
}

// SubmitReportJSONRequestBody defines body for SubmitReport for application/json ContentType.
type SubmitReportJSONRequestBody = NewReportRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// QueryByHash request
	QueryByHash(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitReport request with any body
	SubmitReportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SubmitReport(ctx context.Context, body SubmitReportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) QueryByHash(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryByHashRequest(c.Server, hash)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitReportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitReportRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitReport(ctx context.Context, body SubmitReportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitReportRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewQueryByHashRequest generates requests for QueryByHash
func NewQueryByHashRequest(server string, hash string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hash", runtime.ParamLocationPath, hash)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hash/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitReportRequest calls the generic SubmitReport builder with application/json body
func NewSubmitReportRequest(server string, body SubmitReportJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitReportRequestWithBody(server, "application/json", bodyReader)
}

// NewSubmitReportRequestWithBody generates requests for SubmitReport with any type of body
func NewSubmitReportRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/report")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// QueryByHash request
	QueryByHashWithResponse(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*QueryByHashResponse, error)

	// SubmitReport request with any body
	SubmitReportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitReportResponse, error)

	SubmitReportWithResponse(ctx context.Context, body SubmitReportJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitReportResponse, error)
}

type QueryByHashResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HashQueryResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r QueryByHashResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryByHashResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SubmitReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *NewReportResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r SubmitReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// QueryByHashWithResponse request returning *QueryByHashResponse
func (c *ClientWithResponses) QueryByHashWithResponse(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*QueryByHashResponse, error) {
	rsp, err := c.QueryByHash(ctx, hash, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryByHashResponse(rsp)
}

// SubmitReportWithBodyWithResponse request with arbitrary body returning *SubmitReportResponse
func (c *ClientWithResponses) SubmitReportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitReportResponse, error) {
	rsp, err := c.SubmitReportWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitReportResponse(rsp)
}

func (c *ClientWithResponses) SubmitReportWithResponse(ctx context.Context, body SubmitReportJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitReportResponse, error) {
	rsp, err := c.SubmitReport(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitReportResponse(rsp)
}

// ParseQueryByHashResponse parses an HTTP response from a QueryByHashWithResponse call
func ParseQueryByHashResponse(rsp *http.Response) (*QueryByHashResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryByHashResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HashQueryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseSubmitReportResponse parses an HTTP response from a SubmitReportWithResponse call
func ParseSubmitReportResponse(rsp *http.Response) (*SubmitReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest NewReportResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
