version: "3.7"

services:
  pmss:
    build:
      context: .
      dockerfile: Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pmss
      MARIADB_USER: pmss
      MARIADB_PASSWORD: pmss
    volumes:
      - db:/var/lib/mysql
      - ./mariadb.initdb:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
volumes:
  db: {}