name: Build and Release PMSS

on:
  push:
    tags:
      - 'v*'

# on:
#   release:
#     types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v3

    - name: Checkout git submoduels
      run: git submodule update --init --recursive

    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.20.1"
        project_path: "./pmss/"
        binary_name: "pmss"
